import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Provider } from '@/components/ui/provider';
import { SquareProvider } from '../provider/square.provider';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'ShareSquare Client',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body className={`${roboto.variable}`}>
        <Provider>
          <SquareProvider>{children}</SquareProvider>
        </Provider>
      </body>
    </html>
  );
}
